name: pysjef
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - cxx-compiler
  - c-compiler
  - cmake
  - boost-cpp>=1.71
  - pugixml>=1.10
  - cython>=0.24
  - lxml>=4.0
  - numpy>=1.17
  - pip
  - regex
  - ghostscript
  - versioneer
